version: '3.8'

services:
    gms:
        image: gms-img
        build:
            context: ./
            dockerfile: dockerfile
        environment:
            VIRTUAL_HOST: gms.tonic3.com
            LETSENCRYPT_HOST: gms.tonic3.com
            LETSENCRYPT_EMAIL: itteam@tonic3.com
        restart: unless-stopped

networks:
    default:
        name: nginx-proxy-default
