version: '3.8'

services:
    sharptool-tonic3: &source_service
        image: ${IMAGE}
        build:
            context: ./
            dockerfile: dockerfile
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            CONTAINER_NAME: ${CONTAINER_NAME}
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped

    prod-service:
        <<: *source_service

    dev-service:
        <<: *source_service

networks:
    default:
        name: ${NETWORK}
